### PR TITLE
2 new Windsong Weaver portraits

### PR DESCRIPTION
**Pull request by cooljeanius**
As discussed on Discord. Note, though, that there's a slight problem here: the portraits don't quite fit the usual 400x400 dimensions. I'm not sure if you'd rather just crop some of her shorts off, or if I should ask for a new version, or if they're fine to use as-is...?

### CODE REVIEW

**Comment by knyghtmare** [comment]
Thank you for your patronage. This humbled one is grateful.

**Comment by cooljeanius** [comment]
> Thank you for your patronage. This humbled one is grateful.

Do you have a suggestion for where a Windsong Weaver has a line of dialogue so that I could see how the portrait looks in-game? I generally like to send those back to the artist so she can get an idea of how it came out.

**Comment by knyghtmare** [comment]
> Do you have a suggestion for where a Windsong Weaver has a line of dialogue so that I could see how the portrait looks in-game? I generally like to send those back to the artist so she can get an idea of how it came out.

Just start some survival scenario (Dark Forecast, IoM) as Windsong Weaver as leader (War of Legends RPG Era) and check the dialogue there?

**Comment by knyghtmare** [comment]
Looks good to me 👌 

image

**Pull request merged**
